name: Maven Build

on:
  workflow_call:
jobs:
  Maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "23"
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-dist
          path: |
            target/*.jar
        id: project